spring.datasource:
                  url: jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist = true&allowPublicKeyRetrieval = true&useSSL = false
                  username: root
                  password: root
                  driver-class-name: com.mysql.cj.jdbc.Driver
                  initialization-mode: always

spring.jpa:
           properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
           hibernate.use-new-id-generator-mappings: false
           hibernate.ddl-auto: update

# App Properties

apps:
    jwtSecret:  jwtsecret
    jwtExpirationMs:  86400000

#logging configuration
logging:
     file: Logs/default.log
#Session Management
spring.session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

#Rate Limiter
resilience4j.ratelimiter:
  instances:
    restaurantService:
      limitForPeriod: 2
      limitRefreshPeriod: 4s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#swagger config
app:
  name: Zonions
  api:
    title: Zonions API
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.example.demo
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true